-- AlterTable
ALTER TABLE "ApelConfig" ADD COLUMN IF NOT EXISTS "targetType" VARCHAR(30) NOT NULL DEFAULT 'AREA';
ALTER TABLE "ApelConfig" ADD COLUMN IF NOT EXISTS "targetGaswilIds" JSONB;
ALTER TABLE "ApelConfig" ADD COLUMN IF NOT EXISTS "targetJaringIds" JSONB;
ALTER TABLE "ApelConfig" ADD COLUMN IF NOT EXISTS "attendanceReplyTemplate" TEXT;
ALTER TABLE "ApelConfig" ADD COLUMN IF NOT EXISTS "requireLocation" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "ApelSession" ADD COLUMN IF NOT EXISTS "targetType" VARCHAR(30) NOT NULL DEFAULT 'AREA';
ALTER TABLE "ApelSession" ADD COLUMN IF NOT EXISTS "targetGaswilIds" JSONB;
ALTER TABLE "ApelSession" ADD COLUMN IF NOT EXISTS "targetJaringIds" JSONB;
ALTER TABLE "ApelSession" ADD COLUMN IF NOT EXISTS "attendanceReplyTemplate" TEXT;
ALTER TABLE "ApelSession" ADD COLUMN IF NOT EXISTS "requireLocation" BOOLEAN NOT NULL DEFAULT true;
