version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/fe"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "fe"

  - package-ecosystem: "npm"
    directory: "/apps/be"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "be"
