/**
 * Canonical user-facing terminology.
 *
 * Keep this helper aligned with docs/DENS_CAKRA_GLOSSARY_SYSTEM.md.
 *
 * Technical role codes, route segments, API fields, and persisted enum values
 * remain unchanged for backward compatibility.
 */
export const DOMAIN_TERMS = {
  executiveRole: "Deputi II",
  regionalCommanderRole: "Kepala BIN Daerah (Kabinda)",
  operationalIntelligenceManagerRole: "Manajer Intelijen Operasional",
  operationalIntelligenceManagerShort: "OIM",
  fieldCoordinatorRole: "Koordinator Wilayah (Korwil)",
  adminSystemRole: "Admin Sistem",
  nationalAgency: "Badan Intelijen Negara",
  nationalLeader: "Kepala BIN (KaBIN)",
  deputyUnit: "Kedeputian II",
  deputyLeader: "Deputi II",
  directorateUnit: "Direktorat 21-25",
  directorateLeader: "Direktur 21-25",
  regionalUnit: "BIN Daerah (Binda)",
  regionalLeader: "Kepala BIN Daerah (Kabinda)",
  regionalCoordinator: "Koordinator Wilayah (Korwil)",
  fieldOfficer: "Petugas Wilayah (Gaswil)",
  anevFunction: "Anev",
  systemAccount: "Akun Sistem",
  anevRegencyCity: "Anev Kabupaten/Kota",
  anevBinda: "Anev Binda",
  anevDirectorate: "Anev Direktorat",
  anevDeputy: "Anev Kedeputian",
  personnel: "Personel",
  fieldPersonnel: "Personel Lapangan",
  jaring: "Jaring",
  jaringName: "Nama Jaring",
  jaringAvatar: "Foto Jaring",
  jaringWhatsApp: "Nomor WhatsApp",
  jaringCode: "Kode Jaring",
  jaringCaretaker: "Petugas Wilayah (Gaswil)",
  jaringActive90Days: "Jaring Aktif 90 Hari",
  jaringInactive90Days: "Jaring Tidak Aktif 90 Hari",
  jaringActivity90Days: "Aktivitas Laporan 90 Hari",
  jaringPlacementArea: "Wilayah Penempatan Jaring",
  jaringReport: "Laporan Jaring",
  baket: "Bahan Keterangan (Baket)",
  jaringCoachingHistory: "Riwayat Pembinaan Jaring",
  intelligenceNetworkMap: "Peta Jejaring Intelijen",
  whatsappIntegration: "Integrasi WhatsApp",
  whatsappActivityLog: "Log Aktivitas WhatsApp",
  whatsappNotificationSettings: "Notifikasi WhatsApp",
  smtpSettings: "Pengaturan SMTP",
  roleAccessSettings: "Role dan Hak Akses",
  positionReportingLine: "Jabatan dan Alur Pelaporan",
  adminAccountAccessGroup: "Akun & Akses",
  adminStructureScopeGroup: "Struktur & Cakupan",
  adminReferenceDataGroup: "Referensi Data",
  adminWhatsappEmailGroup: "WhatsApp & Email",
  adminSecurityAuditGroup: "Keamanan & Audit",
  draftBaket: "Draf Baket",
  validatedBaket: "Baket Tervalidasi",
  informationReport: "Laporan Informasi",
  intelligenceReport: "Laporan Intelijen",
  regionalIntelligenceReport: "Laporan Intelijen Binda",
  directorateIntelligenceReport: "Laporan Intelijen Direktorat",
  deputyIntelligenceProduct: "Produk Kedeputian II",
  commandTerritorialLine: "Garis Komando Kewilayahan",
  centralSupervisionLine: "Garis Supervisi BIN Pusat",
  directorateSupervisionScope: "Wilayah Supervisi Direktorat/Ditwil",
  dkiDirectorateSupervisionScope: "Wilayah Supervisi DKI berbasis Kota/Kabupaten",
  bottomUpReportFlow: "Flow Laporan Bottom-Up",
  topDownDirectiveFlow: "Flow Arahan Top-Down",
  assignmentArea: "Wilayah Penugasan",
  fieldOfficerDistrict: "Kecamatan Penugasan",
  registeredJaringLocation: "Wilayah Penempatan Jaring",
  actualReportLocation: "Lokasi Aktual Laporan",
  locationSuitability: "Status Kesesuaian Lokasi dengan Wilayah Penugasan",
  actionView: "Lihat",
  actionCreate: "Buat",
  actionEdit: "Ubah",
  actionVerify: "Verifikasi",
  actionReturnForRevision: "Kembalikan untuk perbaikan",
  actionReject: "Tolak",
  actionApprove: "Setujui",
  actionForward: "Teruskan",
  actionDisposition: "Disposisi",
  actionGiveDirection: "Berikan arahan",
  actionCloseFollowUp: "Tutup tindak lanjut",
  actionExport: "Ekspor",
  actionManageUsers: "Kelola pengguna",
} as const;
