import { RoleCode } from '../../generated/prisma/client.js';

export const DOMAIN_PERMISSION_CODES = [
  'alert.assign',
  'alert.create',
  'alert.execute',
  'alert.read',
  'alert.update',
  'analysis.archive',
  'analysis.create',
  'analysis.read',
  'analysis.update',
  'analysis.validate',
  'approval.cancel',
  'approval.create',
  'approval.decide',
  'approval.read',
  'area.boundary.manage',
  'area.import',
  'area.manage',
  'area.policy.manage',
  'area.policy.read',
  'area.read',
  'area.resolve',
  'area.scope.manage',
  'area.scope.read',
  'assignment.close',
  'assignment.create',
  'assignment.manage',
  'assignment.read',
  'assignment.transfer',
  'audit.export',
  'audit.read',
  'baket.create',
  'baket.read',
  'baket.request-development',
  'baket.submit',
  'baket.update',
  'dashboard.read',
  'directive.acknowledge',
  'directive.cancel',
  'directive.create',
  'directive.distribute',
  'directive.publish',
  'directive.read',
  'directive.track',
  'directive.update',
  'distribution.create',
  'distribution.read',
  'distribution.read-own',
  'distribution.retry',
  'distribution.revoke',
  'distribution.system',
  'emergency.create',
  'emergency.manage',
  'emergency.read',
  'emergency.update',
  'emergency.verify',
  'file.create',
  'file.delete',
  'file.read',
  'integration.manage',
  'integration.read',
  'integration.retry',
  'jaring.coverage.manage',
  'jaring.create',
  'jaring.manage',
  'jaring.read',
  'jaring.transfer',
  'jaring.update',
  'location.read',
  'location.read-history',
  'location.read-own',
  'location.write-own',
  'map.read',
  'notification.read-own',
  'organization.coverage.manage',
  'organization.coverage.read',
  'organization.create',
  'organization.move',
  'organization.read',
  'organization.update',
  'permission.read',
  'position.create',
  'position.read',
  'position.reporting.manage',
  'position.update',
  'product.archive',
  'product.create',
  'product.read',
  'product.submit',
  'product.template.manage',
  'product.template.read',
  'product.update',
  'role.permission.manage',
  'role.read',
  'system.diagnostics.read',
  'system.setting.manage',
  'system.setting.read',
  'task.assign',
  'task.cancel',
  'task.create',
  'task.execute',
  'task.read',
  'task.reassign',
  'task.update',
  'user.activate',
  'user.archive',
  'user.lock',
  'user.provision',
  'user.read',
  'user.suspend',
  'user.unlock',
  'user.update',
  'uuk.cancel',
  'uuk.create',
  'uuk.publish',
  'uuk.read',
  'uuk.update',
  'verification.complete',
  'verification.create',
  'verification.read',
  'verification.update',
  'whatsapp.moderate',
  'whatsapp.read',
  'whatsapp.resolve',
  'whatsapp.route',
  'whatsapp.validate',
] as const;

export type DomainPermissionCode = (typeof DOMAIN_PERMISSION_CODES)[number];

const permissionSet = new Set<DomainPermissionCode>(DOMAIN_PERMISSION_CODES);

function grants(
  prefixes: readonly string[],
  exact: readonly DomainPermissionCode[] = [],
): readonly DomainPermissionCode[] {
  return DOMAIN_PERMISSION_CODES.filter(
    (code) =>
      exact.includes(code) ||
      prefixes.some((prefix) => code.startsWith(`${prefix}.`)),
  );
}

export const DOMAIN_ROLE_PERMISSIONS: Record<
  RoleCode,
  readonly DomainPermissionCode[]
> = {
  [RoleCode.ADMIN_SYSTEM]: grants(
    [
      'user',
      'role',
      'permission',
      'organization',
      'position',
      'assignment',
      'area',
      'integration',
      'audit',
      'system',
      'product.template',
    ],
    ['file.create', 'file.delete', 'file.read', 'notification.read-own'],
  ),
  [RoleCode.EXECUTIVE]: grants(
    ['directive', 'dashboard', 'map', 'emergency', 'alert'],
    [
      'organization.read',
      'position.read',
      'area.read',
      'uuk.read',
      'task.read',
      'assignment.read',
      'baket.read',
      'verification.read',
      'analysis.read',
      'product.read',
      'approval.read',
      'approval.decide',
      'distribution.create',
      'distribution.read',
      'distribution.read-own',
      'distribution.retry',
      'distribution.revoke',
      'file.read',
      'notification.read-own',
      'location.read',
    ],
  ),
  [RoleCode.REGIONAL_COMMANDER]: grants(
    ['uuk', 'task', 'dashboard', 'map', 'emergency', 'alert'],
    [
      'organization.read',
      'position.read',
      'area.read',
      'assignment.read',
      'directive.read',
      'directive.track',
      'directive.acknowledge',
      'jaring.read',
      'baket.read',
      'verification.read',
      'analysis.read',
      'product.read',
      'approval.read',
      'approval.decide',
      'approval.cancel',
      'distribution.create',
      'distribution.read',
      'distribution.read-own',
      'file.read',
      'notification.read-own',
      'location.read',
      'location.read-history',
    ],
  ),
  [RoleCode.OPERATIONAL_INTELLIGENCE_MANAGER]: grants(
    [
      'analysis',
      'product',
      'verification',
      'dashboard',
      'map',
      'emergency',
      'alert',
    ],
    [
      'organization.read',
      'position.read',
      'area.read',
      'assignment.read',
      'directive.read',
      'directive.acknowledge',
      'uuk.read',
      'task.create',
      'task.read',
      'task.assign',
      'task.update',
      'task.cancel',
      'baket.read',
      'baket.request-development',
      'approval.create',
      'approval.read',
      'distribution.create',
      'distribution.read',
      'distribution.read-own',
      'file.create',
      'file.read',
      'notification.read-own',
      'location.read',
    ],
  ),
  [RoleCode.FIELD_COORDINATOR]: grants(
    ['task', 'dashboard', 'map', 'emergency', 'alert'],
    [
      'organization.read',
      'position.read',
      'area.read',
      'assignment.read',
      'directive.read',
      'directive.acknowledge',
      'uuk.read',
      'jaring.read',
      'baket.read',
      'integration.read',
      'integration.manage',
      'file.create',
      'file.read',
      'notification.read-own',
      'location.read',
      'location.read-history',
      'location.read-own',
      'location.write-own',
    ],
  ),
  [RoleCode.FIELD_OFFICER]: grants(
    ['jaring', 'whatsapp'],
    [
      'area.read',
      'assignment.read',
      'task.read',
      'task.execute',
      'baket.create',
      'baket.read',
      'baket.update',
      'baket.submit',
      'map.read',
      'emergency.create',
      'emergency.read',
      'emergency.update',
      'alert.read',
      'alert.execute',
      'file.create',
      'file.read',
      'notification.read-own',
      'location.read-own',
      'location.write-own',
    ],
  ),
};

for (const permissions of Object.values(DOMAIN_ROLE_PERMISSIONS)) {
  for (const permission of permissions) {
    if (!permissionSet.has(permission)) {
      throw new Error(`Unknown domain permission: ${permission}`);
    }
  }
}
